server:
  host: "0.0.0.0"
  port: 9474
  auth:
    user: eventum
    password: eventum

generation:
  timezone: UTC
  batch:
    size: 10000

log:
  level: info

path:
  startup: /app/config/startup.yml
  generators_dir: /app/generators
  logs: /app/logs
  keyring_cryptfile: /app/config/cryptfile.cfg